apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: microprofile-ss-demos
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: microprofile-ss-demos
    app.kubernetes.io/part-of: ss-demos
  name: microprofile-ss-demos
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: microprofile-ss-demos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: microprofile-ss-demos
        app.kubernetes.io/name: microprofile-wildfly
    spec:
      containers:
      - env:
        - name: JGROUPS_PING_PROTOCOL
          value: dns.DNS_PING
        - name: OPENSHIFT_DNS_PING_SERVICE_PORT
          value: "8888"
        - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
          value: "false"
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: microprofile-ping
        - name: ENV_FILES
          value: /etc/extensions/*
        image: quay.io/redhat-user-workloads/jdenise-tenant/ss-demos/microprofile-ss-demos@sha256:9f93a525e4fcf5731045693dde7b6ad93bfa7459e23277d3f9b5c802a2ae6665
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/live
            port: admin
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: microprofile
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9990
          name: admin
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/ready
            port: admin
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
status: {}
