apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: microprofile-ss-demos
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: microprofile-ss-demos
    app.kubernetes.io/part-of: ss-demos
  name: microprofile-ss-demos
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: microprofile-ss-demos
status:
  loadBalancer: {}
