apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: microprofile-ss-demos
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jdenise-tenant/ss-demos/microprofile-ss-demos@sha256:9f93a525e4fcf5731045693dde7b6ad93bfa7459e23277d3f9b5c802a2ae6665
        name: microprofile
        resources: {}
status: {}
