apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: microprofile-ss-demos
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: microprofile-ss-demos
    app.kubernetes.io/part-of: ss-demos
  name: microprofile-ss-demoszn6u
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: microprofile-ss-demos
    weight: null
status: {}
